import "./globals.css";
// import { Inter } from "next/font/google";
import { NextAuthProvider } from "./provider/AuthProvider";
import { DarkThemeProvider } from "./provider/DarkThemeProvider";
import { MessagesProvider } from "./provider/MessagesProvider";
import { UserDetailProvider } from "./provider/UserDetailProvider";


// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextBolt",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <DarkThemeProvider>
        <NextAuthProvider>
          <UserDetailProvider>
            <MessagesProvider>
              {children}
            </MessagesProvider>
          </UserDetailProvider>
        </NextAuthProvider>
        </DarkThemeProvider>
      </body>
    </html>
  );
}
